remote_theme: KyleRego/swiss

title: Kyle Rego
html_title: Kyle Rego - Massachusetts Web Developer
description: Weblog and notes about Physics, CS, and software.
baseurl: ""
url: "https://kylerego.github.io"
email: regoky@outlook.com

github_repo: KyleRego.github.io
github_username: KyleRego

linkedin_url: https://www.linkedin.com/in/kyle-rego-117b25139/

# Build settings
markdown: kramdown
highlighter: rouge

google_analytics: G-B9Y6YW21X4
emoji: 🙃

defaults:
  -
    scope:
      path:            "the-old-website/**/*.html"
    values:
      sitemap:         false

plugins:
  - jekyll-sitemap

collections_dir: collections

collections:
  notes:
    output: true
  linklogs:
    output: true