title: Kyle Rain
html_title: Software developer
description: Development blog with notes on Ruby on Rails and ASP.NET Core web development
baseurl: ""
url: "https://kylerego.github.io"
email: regoky@outlook.com

github_repo: KyleRego.github.io
github_username: KyleRego

linkedin_url: https://www.linkedin.com/in/kyle-rego-117b25139/

# Build settings
markdown: kramdown
highlighter: rouge

google_analytics: G-B9Y6YW21X4
emoji: 🙃

defaults:
  -
    scope:
      path:            "the-old-website/**/*.html"
    values:
      sitemap:         false

plugins:
  - jekyll-sitemap
  - jekyll-feed

collections_dir: collections

collections:
  notes:
    output: true
