title: Kyle Rain
html_title: Software developer
description: Hello, welcome to my blog! I hope you find the information here helpful, but these posts should not be taken as 100% correct ways to do anything.
baseurl: ""
url: "https://eggrain.blog"
email: regoky@outlook.com

github_repo: eggrain.github.io
github_username: eggrain

linkedin_url: https://www.linkedin.com/in/kyle-rego-117b25139/

# Build settings
markdown: kramdown
highlighter: rouge

google_analytics: G-B9Y6YW21X4
emoji: 🙃

defaults:
  -
    scope:
      path:            "the-old-website/**/*.html"
    values:
      sitemap:         false

plugins:
  - jekyll-sitemap
  - jekyll-feed

collections_dir: collections

collections:
  notes:
    output: true
