remote_theme: KyleRego/swiss

title: Kyle Rego
description: A Ruby on Rails weblog that is currently focused on book reviews.
baseurl: ""
url: "https://kylerego.github.io"
email: regoky@outlook.com

github_repo: KyleRego.github.io
github_username: KyleRego

linkedin_url: https://www.linkedin.com/in/kyle-rego-117b25139/

# Build settings
markdown: kramdown
highlighter: rouge

google_analytics: G-B9Y6YW21X4
emoji: 🙃

defaults:
  -
    scope:
      path:            "the-old-website/**/*.html"
    values:
      sitemap:         false

plugins:
  - jekyll-sitemap

collections_dir: collections

collections:
  computer_science_notes:
    output: true
  physics_notes:
    output: true
  software_development_notes:
    output: true