remote_theme: broccolini/swiss

title: Kyle Rego
description: Mostly book reviews probably.
baseurl: ""
url: "https://kylerego.github.io"
github_repo: KyleRego.github.io
github_username: KyleRego

theme_color: black

# Build settings
markdown: kramdown
highlighter: rouge

google_analytics: G-B9Y6YW21X4